bot:
  interval: 5 # in seconds

exchange:
  url:
    test: wss://test.deribit.com/ws/api/v2
    prod: wss://www.deribit.com/ws/api/v2

  env: 'prod'
  trading: true
  daydelta: 1
  order_size: 0.1
  risk_perc: 0.003
  min_prem: 0.005 # 0.006
  strike_dist: 750 # 1500
  dvol_min: 50
  dvol_mid: 60
  expire_time: 6
  max_prem_cnt: 2
  maker: false

  auth:
    test:
      grant_type: 'client_credentials'
      client_id: 'PLwAFl71'
      client_secret: 'fyUfohnmLn9G0vlnPVOMsDFBIWTdsacl7hDF-pzRWl8'
    prod:
      grant_type: 'client_credentials'

  currency: 'BTC'

# See settings from module logging
# https://docs.python.org/3/library/logging.config.html
logging:
  version: 1
  
  formatters:
    simple:
      format: '%(asctime)s %(name)s [%(levelname)s]: %(message)s'
    csv:
      format: '%(asctime)s,%(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

  handlers:
    console:
      # class: 'logging.StreamHandler'
      class: 'logging.handlers.TimedRotatingFileHandler'
      level: 'DEBUG'
      formatter: 'simple'
      filename: 'output_log'
      when: 'midnight'
      # stream: 'ext://sys.stdout'
    file:
      class: 'logging.handlers.TimedRotatingFileHandler'
      level: 'FILE'
      formatter: 'csv'
      filename: 'bot_log'
      when: 'midnight'
      # interval: 2
      # suffix: '%y-%m-%d_%H_%M_bot_log.csv'

  root:
    level: 'INFO'
    handlers: [console,file]
